### ISSUE TITLE
pana does not handle `pubspec_overrides.yaml`

### ISSUE THREAD

**Issue by SunlightBro** [dart-lang/pana#1089]
`freezed` uses a **pubspec_overrides.yaml** file, that overrides to the local `freezed_annotation` during development
```yaml
dependency_overrides:
  freezed_annotation:
    path: ../freezed_annotation
```

But this results in `pana --hosted freezed` to not be able to resolve those dependencies during **✗ Pass static analysis**.

### How to reproduce:
```sh
dart pub global activate pana
pana --hosted freezed
```
Points: 40/120.
```sh
git clone https://github.com/rrousselGit/freezed.git
pana freezed/packages/freezed
```
Points: 100/120.
