### ISSUE TITLE
repository tag in pubspec.yaml incorrectly interpreted by pub.dev

### ISSUE THREAD

**Issue by Alexqwesa** [dart-lang/pana#1252]
pubspec.yaml had a correctly set `repository` tag, but pub.dev says:
 >pubspec.yaml from the repository URL missmatch: expected https://github.com/Alexqwesa/locale_switcher but got null.

[https://pub.dev/packages/locale_switcher](https://pub.dev/packages/locale_switcher)

pubspec.yaml contains:
```yaml
name: locale_switcher
description: A widget for switching the locale of your application with 2 lines of code.
repository: https://github.com/Alexqwesa/locale_switcher
homepage: https://github.com/Alexqwesa/locale_switcher
# ....
```

I also tried to only set `repository` or only set `homepage` - didn't work,

Note: when i first time published package, i made a mistake and set repository wrong...
