### ISSUE TITLE
Don't punish when dependencies hold down other dependencies

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#551]
If we have packages:
```yaml
  name: A
  version: 1.0.0
  dependencies:
    B: 1.0.0
```
```yaml
  name: B
  version: 1.0.0
```
```yaml
  name: B
  version: 1.1.0
```
-----

Then a package D defined as follows will **not** be punished for out-dated dependencies:
```yaml
  name: D
  version: 1.0.0
  dependencies:
    A: ^1.0.0
```

But a package E defined as follows **will be punished** for out-dated dependencies:
```yaml
  name: E
  version: 1.0.0
  dependencies:
    A: ^1.0.0
    B: ^1.0.0
```
