### ISSUE TITLE
linter: missing sdk.version... a little help?

### ISSUE THREAD

**Issue by pq** [dart-lang/pana#591]
As of the lastest `pana` release, the linter's maintenance score has dropped w/ this warning:

```yaml
 "maintenance": {
  "missingChangelog": false,
  "missingExample": false,
  "missingReadme": false,
  "missingAnalysisOptions": false,
  "oldAnalysisOptions": false,
  "strongModeEnabled": true,
  "isExperimentalVersion": false,
  "isPreReleaseVersion": false,
  "suggestions": [
   {
    "code": "sdk.missing",
    "level": "error",
    "title": "No valid SDK.",
    "description": "The analysis could not detect a valid SDK that can use this package.",
    "score": 20.0
   }
  ]
 },

```

Build failure: https://travis-ci.org/dart-lang/linter/jobs/624732589

Linter pubspec: https://github.com/dart-lang/linter/blob/master/pubspec.yaml

Could you help me resolve?

/cc @isoos @jonasfj
