### ISSUE TITLE
"Package does not support Flutter platform Web" but it does?

### ISSUE THREAD

**Issue by passsy** [dart-lang/pana#814]
pana `0.14.9` doesn't detect web support for [wiredash](https://pub.dev/packages/wiredash) although it is fully compatible and all dependencies support it.  

```
### [~] 10/20 points: Supports 2 of 3 possible platforms (**iOS**, **Android**, Web)

Found 9 issues. Showing the first 2:

Consider supporting multiple platforms:

<details>
<summary>
Package does not support Flutter platform Web
</summary>

Because:
* `package:wiredash/wiredash.dart` that imports:
* `package:wiredash/src/wiredash_widget.dart` that imports:
* `package:wiredash/src/wiredash_provider.dart` that imports:
* `package:wiredash/src/feedback/feedback_model.dart` that imports:
* `package:wiredash/src/feedback/data/retrying_feedback_submitter.dart` that imports:
* `package:wiredash/src/feedback/data/pending_feedback_item_storage.dart` that imports:
* `package:shared_preferences/shared_preferences.dart` that imports:
* `package:shared_preferences_windows/shared_preferences_windows.dart` that declares support for platforms: Windows
</details>
```

[`shared_preferences`](https://pub.dev/packages/shared_preferences) itself supports web as platforms, so how can a package depending on `shared_preferences` get a penalty for not supporting web?

[`shared_preferences`](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences/pubspec.yaml) pubspec 

```yaml
name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences
# 0.5.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.5.13

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.sharedpreferences
        pluginClass: SharedPreferencesPlugin
      ios:
        pluginClass: FLTSharedPreferencesPlugin
      linux:
        default_package: shared_preferences_linux
      macos:
        default_package: shared_preferences_macos
      web:
        default_package: shared_preferences_web

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter
  shared_preferences_platform_interface: ^1.0.0
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(franciscojma): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  shared_preferences_linux: ^0.0.2
  shared_preferences_macos: ^0.0.1
  shared_preferences_web: ^0.1.2
  shared_preferences_windows: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    path: ../../integration_test
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
```

[`shared_preferences_windows`](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_windows/pubspec.yaml) pubspec

```yaml
name: shared_preferences_windows
description: Windows implementation of shared_preferences
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_windows
version: 0.0.2

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: SharedPreferencesWindows
        pluginClass: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  shared_preferences_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  file: ">=5.1.0 <7.0.0"
  meta: ^1.1.7
  path: ^1.6.4
  path_provider_platform_interface: ^1.0.3
  path_provider_windows: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
```
