### ISSUE TITLE
Broken import dart:indexed_db in package's Support sound null safety score.

### ISSUE THREAD

**Issue by kithe-raker** [dart-lang/pana#891]
I've just published [my first flutter package](https://pub.dev/packages/network_font).
The package was built with `dart null-safety`, but `pub.dev` said that my package doesn't support **Null safety** with `Broken import dart:indexed_db` issue.

- here is [screenshot](https://user-images.githubusercontent.com/54874488/118401151-ada7d200-b68e-11eb-87a6-344162dff9e0.png)
- `dart pub outdated --mode=null-safety`
```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.
```
- `dart migrate`
```
See https://dart.dev/go/null-safety-migration for a migration guide.

Note: more than one project found; migrating the top-level project.

Analyzing project...
[-----------------------------------------------------------------------------------------------------------------------------------------------------------/]All sources appear to be already migrated.  Nothing to do.
```
- `pubspec.yaml`
```yaml
name: network_font
description: network_font will help you use your custom font from network, so you don't have to store those fonts in your project directory's asset folder.
version: 0.0.4
homepage: https://github.com/kithe-raker/network_font

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Get user's local path
  path_provider: ^2.0.1

  # Make get request to network font
  http: ^0.13.3

  # Store data to user's local
  hive: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
```
